import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Invariants of the synthetic abnormal-baseline hepatic cohort (#93) —
// site/data/adbds-abnbl.csv, generated by scripts/build-hep-abnbl-cohort.mjs.
//
// The modified ALT waterfall (Figure 5 of Amirzadegan et al., Drug Safety
// 2025;48:443-453) can only be demonstrated on a population with abnormal
// baseline ALT, normal baseline bilirubin, and an asymmetric jaundice signal —
// none of which the vendored pilot data carries. This suite asserts that the
// generated cohort really does carry the signal the demo claims, so a
// regeneration that quietly loses it fails here rather than in a screenshot
// nobody reads.
//
// These IDs sit in their own HWF-COHORT-* area: they evidence properties of the
// DEMO DATA, not of the renderer, and must not be confused with the HWF-DATA-*
// requirements the module's own tests satisfy.

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const dataPath = path.join(rootDir, 'site', 'data', 'adbds-abnbl.csv');

const HEADER = 'USUBJID,SITE,SITEID,SEX,RACE,ARM,VISIT,VISITNUM,TEST,STRESU,STRESN,STNRLO,STNRHI';

const ALT = 'Alanine Aminotransferase';
const AST = 'Aspartate Aminotransferase';
const TB = 'Bilirubin';
const ALP = 'Alkaline Phosphatase';
const ANALYTES = [ALT, AST, TB, ALP];

const PLACEBO = 'ABL: Placebo';
const ACTIVE = 'ABL: Study Drug';

const ALT_ULN = 40;
const TB_ULN = 1.2;
const ON_TREATMENT_VISITS = [1, 2, 3, 4];

const raw = readFileSync(dataPath, 'utf8').trim();
const [header, ...lines] = raw.split('\n');
const columns = header.split(',');
const rows = lines.map((line) =>
  Object.fromEntries(line.split(',').map((value, i) => [columns[i], value]))
);

// One record per participant, reduced the way the waterfall reduces it: the
// baseline is the VISITNUM 0 record and the peak is the maximum across the
// on-treatment visits with the baseline record excluded.
const participants = (() => {
  const byId = new Map();
  for (const row of rows) {
    if (!byId.has(row.USUBJID)) {
      byId.set(row.USUBJID, { id: row.USUBJID, arm: row.ARM, site: row.SITE, measures: {} });
    }
    const participant = byId.get(row.USUBJID);
    const measure = (participant.measures[row.TEST] ||= {});
    measure[Number(row.VISITNUM)] = { value: Number(row.STRESN), uln: Number(row.STNRHI) };
  }
  return [...byId.values()].map((participant) => {
    const at = (test, visitn) => participant.measures[test]?.[visitn]?.value;
    const peak = (test) => Math.max(...ON_TREATMENT_VISITS.map((v) => at(test, v)));
    const baselineTb = at(TB, 0);
    const peakTb = peak(TB);
    return {
      ...participant,
      baselineAlt: at(ALT, 0),
      peakAlt: peak(ALT),
      baselineAltUln: at(ALT, 0) / ALT_ULN,
      baselineTbUln: baselineTb / TB_ULN,
      peakTbUln: peakTb / TB_ULN,
      declines: peak(ALT) < at(ALT, 0),
      // The paper's Table-1 cohort rule: normal-enough baseline bilirubin.
      inCohort: baselineTb <= 0.8 * TB_ULN,
      newOnsetJaundice: baselineTb <= TB_ULN && peakTb > TB_ULN
    };
  });
})();

const inArm = (arm) => participants.filter((p) => p.arm === arm);
const countDeclines = (arm) => inArm(arm).filter((p) => p.declines).length;
const countJaundice = (arm) => inArm(arm).filter((p) => p.newOnsetJaundice).length;

describe('abnormal-baseline hepatic demo cohort', () => {
  it('HWF-COHORT-001: every ABL- participant has a day-0 baseline for all four analytes (#93)', () => {
    // The defect this cohort exists to avoid: 24 of 318 participants in
    // adbds.csv have no VISITNUM==0 ALT record and fall back to an unscheduled
    // visit, so their "baseline" is an on-treatment value and their bar can
    // never drop below the baseline trace.
    expect(participants).toHaveLength(80);
    for (const participant of participants) {
      expect(participant.id.startsWith('ABL-')).toBe(true);
      for (const analyte of ANALYTES) {
        const series = participant.measures[analyte];
        expect(series, `${participant.id} ${analyte}`).toBeDefined();
        expect(Number.isFinite(series[0]?.value), `${participant.id} ${analyte} baseline`).toBe(
          true
        );
        for (const visitn of ON_TREATMENT_VISITS) {
          expect(
            Number.isFinite(series[visitn]?.value),
            `${participant.id} ${analyte} ${visitn}`
          ).toBe(true);
        }
      }
    }
  });

  it('HWF-COHORT-002: the file carries the shared measure contract and is labelled synthetic (#93)', () => {
    expect(header).toBe(HEADER);
    expect(rows).toHaveLength(80 * 5 * 4);
    expect(new Set(rows.map((r) => r.SITE))).toEqual(
      new Set(['Hepatology ABN-BL Unit (synthetic)'])
    );
    expect(new Set(rows.map((r) => r.TEST))).toEqual(new Set(ANALYTES));
  });

  it('HWF-COHORT-003: exactly two arms, one placebo and one active, of 40 participants each (#93)', () => {
    const arms = new Set(participants.map((p) => p.arm));
    expect(arms).toEqual(new Set([PLACEBO, ACTIVE]));
    expect(inArm(PLACEBO)).toHaveLength(40);
    expect(inArm(ACTIVE)).toHaveLength(40);
  });

  it('HWF-COHORT-004: ALT carries a single cohort-wide upper limit of normal and a single unit (#93)', () => {
    // An absolute axis needs one reference line: where the range varies the
    // renderer must draw a band instead (HWF-AXIS-004). Here it does not vary.
    const altRows = rows.filter((r) => r.TEST === ALT);
    expect(new Set(altRows.map((r) => r.STNRHI))).toEqual(new Set([String(ALT_ULN)]));
    expect(new Set(altRows.map((r) => r.STNRLO))).toEqual(new Set(['6']));
    expect(new Set(altRows.map((r) => r.STRESU))).toEqual(new Set(['U/L']));
  });

  it('HWF-COHORT-005: the plotted sub-population clears the baseline-bilirubin rule with margin (#93)', () => {
    const cohort = participants.filter((p) => p.inCohort);
    expect(cohort.length).toBeGreaterThanOrEqual(55);
    // No participant sits in the 0.8-1.0xULN no-man's-land, so rounding or a
    // reseeded PRNG cannot move anyone across the exclusion boundary.
    expect(participants.filter((p) => p.baselineTbUln > 0.8 && p.baselineTbUln <= 1)).toHaveLength(
      0
    );
    expect(Math.max(...cohort.map((p) => p.baselineTbUln))).toBeLessThanOrEqual(0.8);
  });

  it('HWF-COHORT-006: an excluded sub-population gives the Table-1 exclusion something to report (#93)', () => {
    const excluded = participants.filter((p) => p.baselineTbUln > 1);
    expect(excluded.length).toBeGreaterThanOrEqual(20);
    expect(Math.min(...excluded.map((p) => p.baselineTbUln))).toBeGreaterThan(1.5);
    expect(Math.max(...excluded.map((p) => p.baselineTbUln))).toBeLessThanOrEqual(4);
    // Every participant is in exactly one of the two sub-populations.
    expect(excluded.length + participants.filter((p) => p.inCohort).length).toBe(
      participants.length
    );
  });

  it('HWF-COHORT-007: exactly six active and one placebo participant develop new-onset jaundice (#93)', () => {
    // The asymmetry is the drug-attributable green-bar signature the figure
    // exists to show; adbds.csv has one per arm, which says nothing.
    expect(countJaundice(ACTIVE)).toBe(6);
    expect(countJaundice(PLACEBO)).toBe(1);
    for (const participant of participants.filter((p) => p.newOnsetJaundice)) {
      expect(participant.baselineTbUln).toBeLessThanOrEqual(0.8);
      expect(participant.peakTbUln).toBeGreaterThan(2.5);
      expect(participant.peakTbUln).toBeLessThanOrEqual(4);
      expect(participant.peakAlt).toBeGreaterThan(2 * participant.baselineAlt);
    }
  });

  it('HWF-COHORT-008: the active arm is skewed toward ALT decreases and the placebo arm is not (#93)', () => {
    // The caption's "large number of bronze bars dropping below baseline".
    expect(countDeclines(ACTIVE)).toBeGreaterThan(countDeclines(PLACEBO));
    expect(countDeclines(ACTIVE)).toBe(24);
    expect(countDeclines(PLACEBO)).toBe(10);
    // The skew survives the cohort rule, so the plotted figure shows it too.
    const plotted = participants.filter((p) => p.inCohort);
    const declines = (arm) => plotted.filter((p) => p.arm === arm && p.declines).length;
    expect(declines(ACTIVE)).toBeGreaterThan(declines(PLACEBO));
  });

  it('HWF-COHORT-009: a declining participant declines at every on-treatment visit (#93)', () => {
    // A bar points down only if the MAXIMUM on-treatment value is below
    // baseline — one high visit anywhere in the series erases the signal.
    for (const participant of participants.filter((p) => p.declines)) {
      for (const visitn of ON_TREATMENT_VISITS) {
        expect(
          participant.measures[ALT][visitn].value,
          `${participant.id} visit ${visitn}`
        ).toBeLessThan(participant.baselineAlt);
      }
    }
  });

  it('HWF-COHORT-010: baseline ALT spans 1-8xULN smoothly across the plotted cohort (#93)', () => {
    // Smoothness is what makes the black baseline trace a unimodal mountain
    // rather than a staircase, and it must hold within each arm because the
    // two arms are ordered back to back around the boundary.
    const baselines = participants
      .filter((p) => p.inCohort)
      .map((p) => p.baselineAltUln)
      .sort((a, b) => a - b);
    expect(baselines[0]).toBeGreaterThanOrEqual(1);
    expect(baselines[0]).toBeLessThanOrEqual(1.1);
    expect(baselines.at(-1)).toBeGreaterThanOrEqual(7.8);
    expect(baselines.at(-1)).toBeLessThanOrEqual(8);
    const gap = (values) => Math.max(...values.slice(1).map((v, i) => v - values[i]));
    expect(gap(baselines)).toBeLessThan(0.5);
    for (const arm of [PLACEBO, ACTIVE]) {
      const armBaselines = participants
        .filter((p) => p.inCohort && p.arm === arm)
        .map((p) => p.baselineAltUln)
        .sort((a, b) => a - b);
      expect(armBaselines.length).toBeGreaterThanOrEqual(25);
      expect(gap(armBaselines), arm).toBeLessThan(0.6);
    }
    // Ties would make the rendered order depend on the tie-break rather than on
    // the data (HWF-ORDER-004); here every baseline is distinct.
    expect(new Set(participants.filter((p) => p.inCohort).map((p) => p.baselineAlt)).size).toBe(
      participants.filter((p) => p.inCohort).length
    );
  });

  it('HWF-COHORT-011: eight active participants carry a peak ALT of 3-6x their own baseline (#93)', () => {
    // The "substantial increases over baseline" tail the paper prioritises for
    // review — and the reason the plotted domain has headroom above the trace.
    const tail = inArm(ACTIVE).filter((p) => p.peakAlt >= 3 * p.baselineAlt);
    expect(tail.length).toBeGreaterThanOrEqual(8);
    for (const participant of tail) {
      expect(participant.peakAlt).toBeLessThanOrEqual(6 * participant.baselineAlt);
    }
    // The tail stays inside a readable axis: the trace tops out at 8xULN and
    // the tallest bar must not flatten it against the floor.
    expect(Math.max(...participants.map((p) => p.peakAlt))).toBeLessThanOrEqual(700);
  });
});
