// Demo mount for the hep-waterfall page (#93): the modified ALT waterfall of
// Amirzadegan et al., Drug Safety 2025;48(5):443-453, Figure 5, against the
// synthetic abnormal-baseline cohort vendored in ./adbds-abnbl.csv (80
// participants, USUBJID prefix ABL-, generated by
// scripts/build-hep-abnbl-cohort.mjs).
//
// WHY THIS DEMO DOES NOT RUN ON THE SHARED adbds.csv. Every other lab renderer
// here mounts against the pharmaverseadam CDISC Pilot 01 extract. This figure
// cannot: measured against that file, after the paper's mandated
// baseline-bilirubin exclusion ZERO of the 234 surviving participants have a
// baseline ALT at or above 3xULN, the whole file carries exactly two
// new-onset-jaundice participants, and the baseline trace is flat and
// discontinuous — so the figure's unimodal baseline "mountain", its green
// jaundice bars, and its arm contrast in below-baseline bars all fail to form.
// The demo therefore runs on a purpose-built synthetic cohort, and the page
// says so above the chart rather than letting a reader mistake it for trial
// data. Provenance: docs/DATA_SOURCES.md.
//
// Three mappings adapt the module defaults to this dataset: measure_values
// points the four liver-measure keys at the dataset's TEST strings, studyday_col
// maps to the numeric VISITNUM sequence (the file carries no study-day column,
// so the visit sequence stands in for study day in the baseline split, the
// tooltip and the listing), and the arm designation names the cohort's two arms
// explicitly so the placebo/active split never depends on auto-detection.
// Loaded by hep-waterfall/index.html after the dist/ bundle.
(function () {
  // Quote-aware CSV parser: the real data may quote fields with embedded
  // commas (e.g. long lab-test names).
  function parseCsv(text) {
    const rows = [];
    let row = [];
    let field = '';
    let inQuotes = false;
    for (let i = 0; i < text.length; i += 1) {
      const char = text[i];
      if (inQuotes) {
        if (char === '"' && text[i + 1] === '"') {
          field += '"';
          i += 1;
        } else if (char === '"') {
          inQuotes = false;
        } else {
          field += char;
        }
      } else if (char === '"') {
        inQuotes = true;
      } else if (char === ',') {
        row.push(field);
        field = '';
      } else if (char === '\n' || char === '\r') {
        if (char === '\r' && text[i + 1] === '\n') i += 1;
        row.push(field);
        rows.push(row);
        row = [];
        field = '';
      } else {
        field += char;
      }
    }
    if (field !== '' || row.length) {
      row.push(field);
      rows.push(row);
    }
    const [header, ...records] = rows.filter(
      (cells) => cells.length > 1 || (cells[0] || '').trim() !== ''
    );
    return records.map(function (cells) {
      return Object.fromEntries(
        header.map(function (col, i) {
          return [col, cells[i] ?? ''];
        })
      );
    });
  }

  // The synthetic-data disclosure, rendered above the chart. The shared demo
  // page template describes the vendored data as a pharmaverseadam extract,
  // which is true of every other renderer and false of this one — so the note
  // is part of the demo mount rather than an afterthought in the guide.
  function renderProvenanceNote(container) {
    const note = document.createElement('p');
    note.className = 'demo-data-note';
    note.style.cssText =
      'margin:0 0 1rem;padding:.6rem .8rem;border-left:3px solid #b5651d;' +
      'background:#fdf6ef;color:#4a3a2c;font-size:.9rem;line-height:1.45';
    note.innerHTML =
      '<strong>This demo runs on synthetic data, not a real trial.</strong> ' +
      'The waterfall serves trials that enrol participants with <em>elevated baseline ALT and ' +
      'normal baseline bilirubin</em>, and the shared demo extract (CDISC Pilot 01, an ' +
      "Alzheimer's study) contains no such population: after the paper's baseline-bilirubin " +
      'exclusion none of its participants reach a baseline ALT of 3×ULN, and it carries two ' +
      'new-onset-jaundice participants in total. <code>adbds-abnbl.csv</code> is therefore a ' +
      'fully synthetic 80-participant cohort (<code>ABL-</code> identifiers, ' +
      '<code>Hepatology ABN-BL Unit (synthetic)</code>) built to carry the figure’s signal. ' +
      'Read the shapes and the controls, not the numbers.';
    container.parentNode.insertBefore(note, container);
  }

  const container = document.querySelector('#container');
  renderProvenanceNote(container);

  fetch('./adbds-abnbl.csv')
    .then(function (response) {
      return response.text();
    })
    .then(function (text) {
      const instance = SafetyViz.hepWaterfall('#container', {
        // The cohort carries no study-day column; VISITNUM (0 = Baseline,
        // 1-4 = on-treatment) is the study-day surrogate, exactly as in the
        // hep-explorer demo.
        studyday_col: 'VISITNUM',
        visit_col: 'VISIT',
        visitn_col: 'VISITNUM',
        measure_values: {
          ALT: 'Alanine Aminotransferase',
          AST: 'Aspartate Aminotransferase',
          TB: 'Bilirubin',
          ALP: 'Alkaline Phosphatase'
        },
        // Name the two arms rather than relying on the /placebo|control/i
        // auto-detect: the side a participant's bar sits on is structural
        // here, and a demo should not depend on a string heuristic.
        arm_col: 'ARM',
        placebo_arm: 'ABL: Placebo',
        active_arms: ['ABL: Study Drug'],
        filters: [
          { value_col: 'SEX', label: 'Sex' },
          { value_col: 'RACE', label: 'Race' }
        ]
      });
      window.__safetyHepWaterfallInstance = instance;
      instance.init(parseCsv(text));
    })
    .catch(function (error) {
      console.error(error);
      container.textContent = 'Failed to load demo data: ' + error.message;
    });
})();
